### PR TITLE
PLAT-100154: Link develop Enact in theme library Travis

### PR DESCRIPTION
**Pull request by JayCanuck**
Adds setup steps to clone `develop` of Enact, bootstrap Enact, and use it linked into sandstone.

Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

### CODE REVIEW

**Comment by ryanjduffy** [comment]
I don't think we want this, actually. Since moonstone isn't under active development, it might be best to leave it using the versions tagged in package.json.

Thoughts??

**Comment by JayCanuck** [comment]
If we aren't planning any further meaningful development on moonstone (the implication of keeping it in-sync with `develop` Enact core major releases) then absolutely, yes, we should freeze it to use existing defaults in `package.json` files.

**Comment by ryanjduffy** [comment]
That's my expectation. Any changes would likely be product-driven hotfixes. They might require an enact hotfix but we'll have to coordinate them at that time.

**Comment by ryanjduffy** [comment]
Closing for now and we can resurrect later if necessary.

**Pull request closed without merging**
